version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.2
    container_name: elasticsearch
    ports:
      - 9201:9200
    environment:
      - cluster.name=docker-cluster
      - xpack.security.enabled=true
      - index.refresh_interval = 5s
      - index.number_of_replicas = 1
      - index.translog.flush_threshold_ops = 50000
      - index.translog.flush_threshold_size = 1.5gb
      - indices.store.throttle.max_bytes_per_sec = 20mb
      - search.max_open_scroll_context = 500
      - cluster.routing.allocation.disk.watermark.low = 85%
      - cluster.routing.allocation.disk.watermark.high = 90%
      - discovery.seed_hosts=localhost
      
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    
  flask_elastic_app:
    build: 
      context: ./service_for_elasticsearch
    depends_on:
      - elasticsearch
    container_name: service
    ports:
      - 8590:5000
    environment:
      PYTHONUNBUFFERED: 0
      ELASTICSEARCH_URL: "http://elasticsearch:9200"
      ELASTICSEARCH_OLD_INDEX: 'araks_index'
      ELASTICSEARCH_INDEX: 'araks_index_v2'
      AMAZON_URL: 'https://araks-projects-develop.s3.amazonaws.com/'

    restart: always

volumes:
  elasticsearch_data:
