version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.2
    container_name: elasticsearch
    ports:
      - 9201:9200
    environment:
      - cluster.name=docker-cluster
      - cluster.initial_master_nodes=elasticsearch1
      - node.name=elasticsearch1
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - index.refresh_interval = 5s
      - index.number_of_replicas = 1
      - index.translog.flush_threshold_ops = 50000
      - index.translog.flush_threshold_size = 1.5gb
      - indices.store.throttle.max_bytes_per_sec = 20mb
      - search.max_open_scroll_context = 500
      - cluster.routing.allocation.disk.watermark.low = 85%
      - cluster.routing.allocation.disk.watermark.high = 90%
      - discovery.seed_hosts=[]
      # - cluster.initial_master_nodes=elasticsearch1
      - path.data=/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    
  flask_elastic_app:
    build: 
      context: ./service_for_elasticsearch
    depends_on:
      - elasticsearch
    container_name: service
    ports:
      - 8590:5000
    environment:
      PYTHONUNBUFFERED: 0
      ELASTICSEARCH_URL: ${ELASTICSEARCH_URL}
      ELASTICSEARCH_INDEX: ${ELASTICSEARCH_INDEX}
      ELASTICSEARCH_NEW_INDEX: ${ELASTICSEARCH_NEW_INDEX}
      AMAZON_URL: ${AMAZON_URL}
      DB_NAME : ${DB_NAME}
      DB_USER : ${DB_USER} 
      DB_HOST : ${DB_HOST}
      DB_PASSWORD : ${DB_PASSWORD}
      DB_PORT : ${DB_PORT}

    restart: always

volumes:
  elasticsearch_data:
