version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.2
    container_name: elasticsearch
    ports:
      - 9200:9200
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms750m -Xmx750m
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

  flask_app:
    build: ./service_for_elasticsearch
    depends_on:
      - elasticsearch
    container_name: service
    ports:
      - 5000:5000
    environment:
      PYTHONUNBUFFERED: 0
      ELASTICSEARCH_URL: "http://elasticsearch:9200"

volumes:
  elasticsearch_data: