version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.2
    container_name: elasticsearch
    ports:
      - 9201:9200
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms2G -Xmx2G
      - cluster.routing.allocation.disk.watermark.low=85%
      - cluster.routing.allocation.disk.watermark.high=95%
      - cluster.info.update.interval=1m
      - index.refresh_interval=1s
      - index.number_of_replicas=0
      - index.translog.flush_threshold_ops=50000
      - index.translog.flush_threshold_size=1.5gb
      - indices.store.throttle.max_bytes_per_sec=20mb
      - threadpool.bulk.type=fixed
      - threadpool.bulk.size=8
      - threadpool.bulk.queue_size=1000
      - index.merge.scheduler.max_thread_count=2
      - search.max_open_scroll_context=500

    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

  flask_elastic_app:
    build: 
      context: ./service_for_elasticsearch
    depends_on:
      - elasticsearch
    container_name: service
    ports:
      - 8590:5000
    environment:
      PYTHONUNBUFFERED: 0
      ELASTICSEARCH_URL: "http://elasticsearch:9200"
      ELASTICSEARCH_INDEX: 'araks_index'
      AMAZON_URL: 'https://araks-projects-develop.s3.amazonaws.com/'

    restart: always

volumes:
  elasticsearch_data:
